import { useState } from 'react'
import { ArrowUpRight, BrainCircuit, Check, Code2, Database, GraduationCap, Lightbulb, Mail, Menu, Radar, Route, Send, Sparkles, Target, X } from 'lucide-react'
import './App.css'

const navItems = [['About', 'about'], ['Skills', 'skills'], ['Projects', 'projects'], ['Certifications', 'certifications'], ['Contact', 'contact']]
const skills = [{ label: 'Python', icon: Code2 }, { label: 'C', icon: Code2 }, { label: 'Flutter', icon: Code2 }, { label: 'Git', icon: Route }, { label: 'GitHub', icon: Code2 }, { label: 'Jupyter Notebook', icon: Database }, { label: 'Google Colab', icon: BrainCircuit }, { label: 'VS Code', icon: Code2 }]
const learning = [['01', 'Web Development', 'Turning ideas into thoughtful, usable interfaces.', Code2], ['02', 'OOP using Python', 'Building cleaner logic with reusable systems.', BrainCircuit], ['03', 'Data Structures & Algorithms', 'Sharpening the way I solve complex problems.', Radar], ['04', 'Design Thinking', 'Finding human-centered paths to better solutions.', Lightbulb]]
const certifications = [['Google for Startups', '01', Target], ['Python Certification - IBM', '02', Code2], ['Wadhwani Venture', '03', Sparkles], ['Hacksprint Hackathon', '04', GraduationCap]]

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [submitted, setSubmitted] = useState(false)
  const scrollTo = (id) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false) }

  return (
    <div className="site-shell">
      <header className="navbar"><button className="brand" onClick={() => scrollTo('home')}><span className="brand-mark">S<span>.</span></span><span>SHREYA M</span></button><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button><nav className={menuOpen ? 'open' : ''}><button onClick={() => scrollTo('home')}>Home</button>{navItems.map(([label, id]) => <button key={id} onClick={() => scrollTo(id)}>{label}</button>)}</nav><button className="nav-cta" onClick={() => scrollTo('contact')}>Let's connect <ArrowUpRight size={16} /></button></header>
      <main>
        <section className="hero" id="home"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> Available for new ideas</p><h1>Curious mind.<br /><em>Data in motion.</em></h1><p className="hero-text">Hi, I'm Shreya - a B.Tech AI & Data Science student exploring the space where intelligent systems meet meaningful experiences.</p><div className="hero-actions"><button className="button button-primary" onClick={() => scrollTo('projects')}>View my projects <ArrowUpRight size={17} /></button><button className="button button-quiet" onClick={() => scrollTo('contact')}>Let's connect <span>↗</span></button></div></div><div className="hero-art" aria-label="Abstract data visualization"><div className="art-label">AI / DS <span>001</span></div><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="core"><BrainCircuit size={50} strokeWidth={1.2} /></div><span className="data-point p-one" /><span className="data-point p-two" /><span className="data-point p-three" /><span className="art-caption">LEARNING<br /><b>IN PUBLIC</b></span></div><div className="hero-index">SCROLL TO EXPLORE <span>↓</span></div></section>
        <section className="section about" id="about"><div className="section-intro"><p className="eyebrow">01 / About me</p><h2>Building a future<br />with <em>intention.</em></h2></div><div className="about-content"><p className="lead">B.Tech AI & Data Science student at Reva University, exploring Data Analysis, Machine Learning and Data Visualization.</p><p>I'm passionate about programming, technology and building innovative solutions that can create real-world impact. Every project is a chance to ask better questions, learn something new and make a useful thing.</p><div className="stats"><div><strong>B.Tech</strong><span>AI & Data Science</span></div><div><strong>Focus</strong><span>AI & Machine Learning</span></div><div><strong>Interests</strong><span>Data Analysis & Visualization</span></div></div></div></section>
        <section className="section skills-section" id="skills"><div className="section-intro"><p className="eyebrow">02 / Toolkit</p><h2>Tools for turning<br /><em>thought into form.</em></h2></div><div className="skills-grid">{skills.map(({ label, icon: Icon }) => <div className="skill" key={label}><Icon size={18} /><span>{label}</span><Check size={14} className="skill-check" /></div>)}</div></section>
        <section className="section learning"><div className="section-intro"><p className="eyebrow">03 / In progress</p><h2>Always becoming<br /><em>something more.</em></h2></div><div className="learning-grid">{learning.map(([number, title, copy, Icon]) => <article className="learning-card" key={title}><span className="card-number">{number}</span><Icon size={29} strokeWidth={1.3} /><h3>{title}</h3><p>{copy}</p><span className="card-arrow">↗</span></article>)}</div></section>
        <section className="section projects" id="projects"><div className="section-intro project-heading"><p className="eyebrow">04 / Selected work</p><h2>Ideas, made<br /><em>tangible.</em></h2><p>Two projects where curiosity met a real-world problem.</p></div><div className="project-list"><article className="project-card pulse"><div className="project-visual"><div className="pulse-grid" /><div className="pulse-line" /><span className="visual-tag">LIVE PROTOTYPE</span><span className="visual-code">PX / 24</span></div><div className="project-info"><span className="project-type">01 / AI + HEALTHCARE</span><h3>PulseX - Early<br />Health Risk Detection</h3><p>An AI-powered healthcare concept that uses smartwatch health data to identify potential health risks at an early stage.</p><div className="tags"><span>AI</span><span>Healthcare</span><span>Machine Learning</span><span>Smartwatch</span></div><a className="text-link" href="https://pulsexx.lovable.app/" target="_blank" rel="noreferrer">View prototype <ArrowUpRight size={17} /></a></div></article><article className="project-card blind"><div className="project-visual"><div className="stick-visual"><Radar size={92} strokeWidth={1} /><div className="signal signal-a" /><div className="signal signal-b" /></div><span className="visual-tag">IOT SYSTEM</span><span className="visual-code">SB / 23</span></div><div className="project-info"><span className="project-type">02 / IOT + ACCESSIBILITY</span><h3>Smart Blind<br />Stick</h3><p>An IoT-based assistive technology project designed to help visually impaired individuals detect obstacles through vibration and sound alerts.</p><div className="tags"><span>IoT</span><span>Arduino</span><span>Sensors</span><span>Embedded Systems</span></div><a className="text-link muted" href="#">View project <ArrowUpRight size={17} /></a></div></article></div></section>
        <section className="section certifications" id="certifications"><div className="section-intro"><p className="eyebrow">05 / Milestones</p><h2>Proof of<br /><em>showing up.</em></h2></div><div className="cert-list">{certifications.map(([title, number, Icon]) => <div className="cert" key={title}><span>{number}</span><Icon size={22} /><h3>{title}</h3><ArrowUpRight size={17} /></div>)}</div></section>
        <section className="contact-section" id="contact"><div className="contact-intro"><p className="eyebrow">06 / Contact</p><h2>Let's build something<br /><em>together.</em></h2><p>I'm always interested in learning, building innovative projects, and connecting with people passionate about technology.</p><div className="contact-links"><a href="https://www.linkedin.com/in/shreya-m-0a8024375" target="_blank" rel="noreferrer"><Code2 size={18} /> LinkedIn <ArrowUpRight size={15} /></a><a href="mailto:sgmuddatnur@gmail.com"><Mail size={18} /> Email <ArrowUpRight size={15} /></a><a href="#"><Code2 size={18} /> GitHub <ArrowUpRight size={15} /></a></div></div><form className="contact-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }}><label>Name<input required name="name" placeholder="Your name" /></label><label>Email<input required type="email" name="email" placeholder="you@example.com" /></label><label>Message<textarea required name="message" placeholder="Tell me a little about your idea..." rows="4" /></label><button className="button button-primary" type="submit">{submitted ? <>Message ready <Check size={17} /></> : <>Send message <Send size={16} /></>}</button>{submitted && <p className="success">Thanks, Shreya will be in touch.</p>}</form></section>
      </main>
      <footer><div className="footer-brand"><span className="brand-mark">S<span>.</span></span><strong>SHREYA M</strong></div><p>Building. Learning. Innovating.</p><div className="footer-right"><span>© 2026 Shreya. All rights reserved.</span><div><a href="https://www.linkedin.com/in/shreya-m-0a8024375" target="_blank" rel="noreferrer"><Code2 size={17} /></a><a href="mailto:sgmuddatnur@gmail.com"><Mail size={17} /></a><a href="#"><Code2 size={17} /></a></div></div></footer>
    </div>
  )
}

export default App
